### ISSUE TITLE
[MCZ Herp R-53968] Chamaeleo b lataeniatus - specificEpithet problem

### ISSUE THREAD

**Issue by tucotuco** [mcz-vertnet/mcz-subset-for-vertnet#15]
This and two other MCZ Chamaeleo specimens have "b" as the specificEpithet.

.....................................................

You can [view the original detail page](http://portal.vertnet.org/o/mcz/herp?id=r-53968) on VertNet. Here are the original record contents:
<table>undefined</table>

**Comment by heliumcell** [comment]
Fixed by collection
