### ISSUE TITLE
[MCZ Herp R-46112] Cryptoblepharus b africanus - specificEpithet problem

### ISSUE THREAD

**Issue by tucotuco** [mcz-vertnet/mcz-subset-for-vertnet#16]
This and one other MCZ Cryptoblepharus specimen has "b" as the specificEpithet.

.....................................................

You can [view the original detail page](http://portal.vertnet.org/o/mcz/herp?id=r-46112) on VertNet. Here are the original record contents:
<table>undefined</table>

**Comment by heliumcell** [comment]
Fixed by collection
