### ISSUE TITLE
[MCZ Herp R-54118] Kinixys b nogneyi - specificEpithet problem

### ISSUE THREAD

**Issue by tucotuco** [mcz-vertnet/mcz-subset-for-vertnet#17]
This specimen has "b" as a specificEpithet.

.....................................................

You can [view the original detail page](http://portal.vertnet.org/o/mcz/herp?id=r-54118) on VertNet. Here are the original record contents:
<table>undefined</table>

**Comment by heliumcell** [comment]
The correct identification has been added by the collection
