### ISSUE TITLE
[MCZ Herp R-37252] Chamaeleo chameleon chameleon - specificEpithet misspelled

### ISSUE THREAD

**Issue by tucotuco** [mcz-vertnet/mcz-subset-for-vertnet#18]
This and three other specimens have "chameleon" rather than "chamaeleon" as the specificEpithet.

.....................................................

You can [view the original detail page](http://portal.vertnet.org/o/mcz/herp?id=r-37252) on VertNet. Here are the original record contents:
<table>undefined</table>

**Comment by heliumcell** [comment]
Fixed by the collection
