### ISSUE TITLE
[MCZ Herp R-96834] Chameleo chameleon - genus misspelled

### ISSUE THREAD

**Issue by tucotuco** [mcz-vertnet/mcz-subset-for-vertnet#19]
This specimen has "Chameleo" as the genus rather than "Chamaeleo".

.....................................................

You can [view the original detail page](http://portal.vertnet.org/o/mcz/herp?id=r-96834) on VertNet. Here are the original record contents:
<table>undefined</table>

**Comment by heliumcell** [comment]
This misspelling has been fixed by the collection.
