### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by heliumcell** [mcz-vertnet/mcz-subset-for-vertnet#30]
Test

**Comment by mmhkennedy** [comment]
Test

**Comment by mmhkennedy** [comment]
Did you get an email from vertnet about these?
I didn’t.

**Comment by heliumcell** [comment]
Well I was closing them so I don't think it sends me a mail. I'm not sure Herps has fixed all of theirs. Doesn't look like it.

Sent from my iPad

On Feb 19, 2015, at 12:55 PM, mmhkennedy <notifications@github.com<mailto:notifications@github.com>> wrote:

Did you get an email from vertnet about these?
I didn’t.
