### ISSUE TITLE
County Spelling Errors in 23 Records

### ISSUE THREAD

**Issue by dbloom** [mcz-vertnet/mcz-subset-for-vertnet#37]
Hello MCZ,

The good folks at the Kentucky Department of Fish & Wildlife Resources, Fish and Wildlife Information System (KFWIS) have identified 23 records in the VertNet data portal that have errors that can be fixed easily.

The records below all contain COUNTY names that are misspelled. This county name should be spelled as "Boone". If you wish to communicate with anyone at KFWIS, let me know and I'll connect you.

institutioncode collectioncode catalognumber county
MCZ	Mamm	BOM-9051	Boon
MCZ	Mamm	BOM-9052	Boon
MCZ	Mamm	BOM-3526	Boon
MCZ	Mamm	BOM-3527	Boon
MCZ	Mamm	BOM-3529	Boon
MCZ	Mamm	BOM-3530	Boon
MCZ	Mamm	BOM-3532	Boon
MCZ	Mamm	BOM-3534	Boon
MCZ	Mamm	BOM-3535	Boon
MCZ	Mamm	BOM-3952	Boon
MCZ	Mamm	BOM-2045	Boon
MCZ	Mamm	BOM-2391	Boon
MCZ	Mamm	BOM-3528	Boon
MCZ	Mamm	BOM-3531	Boon
MCZ	Mamm	BOM-3533	Boon
MCZ	Mamm	BOM-3536	Boon
MCZ	Mamm	BOM-3537	Boon
MCZ	Mamm	BOM-3538	Boon
MCZ	Mamm	BOM-3539	Boon
MCZ	Mamm	BOM-3941	Boon
MCZ	Mamm	BOM-3942	Boon
MCZ	Mamm	BOM-3946	Boon
MCZ	Mamm	BOM-3950	Boon

**Comment by mmhkennedy** [comment]
The county for these records has been changed to "Boone."

**Comment by dbloom** [comment]
Perfect.

As a side note, it is a good practice to "close" an issue when it has been resolved so that everyone - including you - knows the issue has been resolved.  I will do it this time.  Thanks!

**Comment by mmhkennedy** [comment]
Thanks.  I will.
