### ISSUE TITLE
2 records with future event dates

### ISSUE THREAD

**Issue by dbloom** [mcz-vertnet/mcz-subset-for-vertnet#74]
A kind and considerate user of the VertNet portal has notified us that the MCZ collection contains 2 records with events dates from the future (1 Mamm, 1 Orn). We recommend that you either make room in your collection for these specimens that have yet to arrive OR please check and revise the dates in your local database.

You can take a look at the records in question via this document, 
[MCZ_Verts_Future_Dates.txt](https://github.com/mcz-vertnet/mcz-subset-for-vertnet/files/953311/MCZ_Verts_Future_Dates.txt)

When you've updated the records, let us know and we'll update your data in VertNet and in other portals. Of course, let us know if you have any questions.

**Comment by heliumcell** [comment]
Both of these dates have been fixed in the database. The corrections should appear in our IPT within 7 days at the most.
